config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  scope 'api' do
    get 'material/list' => 'material#list'
    get 'material/edit' => 'material#edit'
    get 'photo/list' => 'photo#list'
    get 'photo/list' => 'photo#list'
    get 'photo/overlay' => 'photo#overlay'
    get 'photo/window' => 'photo#window'
    get 'video/list' => 'video#list'
    get 'video/edit' => 'video#edit'
    get 'quotes/list' => 'quotes#list'
    get 'quotes/edit' => 'quotes#edit'
    get 'main/list' => 'main#list'
    get 'main/edit' => 'main#edit'
    resources :feedback, :video, :home, :photo, :tag, :material, :quotes, :main, shallow: true #, only: [:index, :show, :create, :update, :destroy]
  end

  get 'admin' => 'application#index'
  get 'admin/app.js' => 'application#app'
  get 'admin/lib.js' => 'application#lib'
  match 'admin/*path' => 'application#index', :via => [:get]

  match '*path' => 'main#index', :via => [:get]

end

app/models/main.rb
class Main < ActiveRecord::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  respond_to :json
  #skip_before_filter :verify_authenticity_token
  before_action :authenticate_user!, :except => [:index, :show] #:update, :create, :destroy, :new]

  def index
    render file: Rails.public_path + 'index.html'
  end

  def create
    @main = Main.new(permit)
    @main.save
    render :json => @main
  end

  def update
    @main = Main.update(params[:id], permit)

    @main.save
    
    render :json => @main
  end

  def destroy
    @main = Main.find_by_id(params[:id])
    render :json => @main.destroy
  end

  def show
    @main = Main.find_by_id(params[:id])
    render :json => @main
  end

  def edit
    respond_to do |format|
      format.html
    end
  end

  private

  def permit
    params.require(:main).permit(:content)
  end

end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  before_action :set_main, only: [:show, :edit, :update, :destroy]

  # GET /mains
  # GET /mains.json
  def index
    @mains = Main.all
  end

  # GET /mains/1
  # GET /mains/1.json
  def show
  end

  # GET /mains/new
  def new
    @main = Main.new
  end

  # GET /mains/1/edit
  def edit
  end

  # POST /mains
  # POST /mains.json
  def create
    @main = Main.new(main_params)

    respond_to do |format|
      if @main.save
        format.html { redirect_to @main, notice: 'Main was successfully created.' }
        format.json { render :show, status: :created, location: @main }
      else
        format.html { render :new }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mains/1
  # PATCH/PUT /mains/1.json
  def update
    respond_to do |format|
      if @main.update(main_params)
        format.html { redirect_to @main, notice: 'Main was successfully updated.' }
        format.json { render :show, status: :ok, location: @main }
      else
        format.html { render :edit }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mains/1
  # DELETE /mains/1.json
  def destroy
    @main.destroy
    respond_to do |format|
      format.html { redirect_to mains_url, notice: 'Main was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main
      @main = Main.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def main_params
      params.require(:main).permit(:content)
    end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/views/mains/_form.html.erb
<%= form_for(@main) do |f| %>
  <% if @main.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@main.errors.count, "error") %> prohibited this main from being saved:</h2>

      <ul>
      <% @main.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mains/edit.html.erb
<h1>Editing Main</h1>

<%= render 'form' %>

<%= link_to 'Show', @main %> |
<%= link_to 'Back', mains_path %>

app/views/mains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mains</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mains.each do |main| %>
      <tr>
        <td><%= main.content %></td>
        <td><%= link_to 'Show', main %></td>
        <td><%= link_to 'Edit', edit_main_path(main) %></td>
        <td><%= link_to 'Destroy', main, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Main', new_main_path %>

app/views/mains/new.html.erb
<h1>New Main</h1>

<%= render 'form' %>

<%= link_to 'Back', mains_path %>

app/views/mains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @main.content %>
</p>

<%= link_to 'Edit', edit_main_path(@main) %> |
<%= link_to 'Back', mains_path %>